### ISSUE TITLE
makeInstance() got an unexpected keyword argument 'bend'

### ISSUE THREAD

**Issue by miguelsousa** [LettError/ufoProcessor#10]
Ran into this problem while working on https://github.com/adobe-type-tools/afdko/issues/402.
Any idea of what may be amiss?

```python
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/ufoProcessor/__init__.py", line 118, in build
    r = document.generateUFO(processRules=processRules)
  File "/lib/python3.6/site-packages/ufoProcessor/__init__.py", line 300, in generateUFO
    font = self.makeInstance(instanceDescriptor, processRules, glyphNames=glyphNames, pairs=pairs, bend=bend)
  File "/lib/python3.6/site-packages/ufoProcessor/__init__.py", line 629, in makeInstance
    kerningObject = kerningMutator.makeInstance(locHorizontal, bend=bend)
TypeError: makeInstance() got an unexpected keyword argument 'bend'
```

**Comment by LettError** [comment]
The new keyword argument is [this change](https://github.com/LettError/MutatorMath/blob/master/Lib/mutatorMath/objects/mutator.py#L212). Sometimes it is necessary to not apply the bends when making an instance. Unrelated, same file, [this discussion](https://github.com/LettError/MutatorMath/commit/085502b7a2dea4b10b7f52dae2b2f6ed04754fdb#commitcomment-31146020) snagged it. It was in a separate branch, I'm not sure why it got into the master at this time.

(Aside, it used to be that github would send me mails for issues, now I need to look at the site to see them - I missed this)

**Comment by miguelsousa** [comment]
@LettError your references go to the **MutatorMath** repository. I don't understand how they relate to the traceback I posted above which is all about **ufoProcessor**.

**Comment by LettError** [comment]
I understand. `kerningMutator.makeInstance(locHorizontal, bend=bend)` can either be a `mutatorMath.Mutator` or a `VariationModelMutator`. The latter already has support for the bend flag, the mutatorMath one just made it to the master. Does your problem persist with an up to date MutatorMath?
